export const FETCH_JSON_DATA = 'FETCH_JSON_DATA';
export const SET_INTENT_MAP = 'SET_INTENT_MAP';
export const SET_KEYWORD_RESULT = 'SET_KEYWORD_RESULT';
export const SET_KEYWORD_DIFFICULTY = 'SET_KEYWORD_DIFFICULTY';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const SET_KEYWORD_METRIC = 'SET_KEYWORD_METRIC';